export const homeBtn  = require('../assets/home.png')
export const bell  = require('../assets/bell.png')
export const scanner  = require('../assets/Scanner.png')
export const eye  = require('../assets/Eye.png')
export const uptick  = require('../assets/Uptick.png')
export const gift  = require('../assets/gift.png')
export const rightArrow  = require('../assets/ChevronRight.png')
export const star  = require('../assets/star.png')
export const Swap  = require('../assets/Swap.png')
export const book  = require('../assets/book.png')
export const trending  = require('../assets/trending-up.png')
export const dollar  = require('../assets/dollar.png')
export const wallet  = require('../assets/wallet.png')
export const clock  = require('../assets/clock.png')
export const setting  = require('../assets/setting.png')


