export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE= "LOGIN_FAILURE";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const GET_ALLPROFILE_REQUEST = "GET_ALLPROFILE_REQUEST";
export const GET_ALLPROFILE_SUCCESS = "GET_ALLPROFILE_SUCCESS";
export const GET_ALLPROFILE_FAILURE = "GET_ALLPROFILE_FAILURE";

export const GET_MYPROFILE_REQUEST = "GET_MYPROFILE_REQUEST";
export const GET_MYPROFILE_SUCCESS = "GET_MYPROFILE_SUCCESS";
export const GET_MYPROFILE_FAILURE = "GET_MYPROFILE_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";